### ISSUE TITLE
maintenance upgrade does not upgrade iobroker

### ISSUE THREAD

**Issue by agross** [buanet/ioBroker.docker#233]
```sh
$ docker exec -it iobroker_app_1 bash
root@iobroker:/opt/iobroker# maintenance upgrade --yes
You are now going to upgrade your js-controller.
As this will change data in /opt/iobroker, make sure you have a backup!
During the upgrade process the container will automatically switch into maintenance mode and stop ioBroker.
Depending of the restart policy, you container will be stoped/ restarted automatically after the upgrade.
Do you want to continue [yes/no]? yes
Activating maintenance mode...
Done.
Stopping ioBroker...
Done.
Upgrading js-controller...
 Objects database error: connect ECONNREFUSED 127.0.0.1:9001
 (several more...)
 Cannot find view "system" for search "host" : Connection is closed.
Error: Object "system.config" not found
```

After 30 minutes I cancelled the task. `docker top iobroker_app_1` shows that the process seems to hang during `iobroker update`:

```sh
$ docker top iobroker_app_1
UID                 PID                 PPID                C                   STIME               TTY                 TIME                CMD
root                1014359             1014338             0                   Dec21               ?                   00:00:00            /bin/bash /opt/scripts/iobroker_startup.sh
root                3344563             1014338             0                   13:35               pts/1               00:00:00            bash
root                3344725             3344563             0                   13:35               pts/1               00:00:00            /bin/bash /opt/scripts/maintenance.sh upgrade --yes
pi                  3344751             1014359             0                   13:35               ?                   00:00:00            adb -L tcp:5037 fork-server server --reply-fd 4
root                3344752             3344725             0                   13:35               pts/1               00:00:00            /bin/bash /usr/bin/iobroker update
pi                  3344756             3344752             0                   13:35               pts/1               00:00:01            node /opt/iobroker/node_modules/iobroker.js-controller/iobroker.js update
root                3344801             1014359             0                   13:36               ?                   00:00:00            tail -f /dev/null
```

**Comment by agross** [comment]
After killing the hanging process (`node /opt/iobroker/node_modules/iobroker.js-controller/iobroker.js update`) with `kill -9 3344756` the maintenance script moved on:

```
/usr/bin/iobroker: line 6: 1318403 Killed                  gosu iobroker node /opt/iobroker/node_modules/iobroker.js-controller/iobroker.js $@
Host    "iobroker"       is up to date. (I upgradede iobroker.js-controller manually in the meantime.)
Done.
Container will be stopped/ restarted in 5 seconds...
Terminated
root@iobroker:/opt/iobroker# %
```

**Comment by buanet** [comment]
> ```shell
> Upgrading js-controller...
>  Objects database error: connect ECONNREFUSED 127.0.0.1:9001
>  (several more...)
>  Cannot find view "system" for search "host" : Connection is closed.
> Error: Object "system.config" not found
> ```

@Apollon77 Have you seen this before? What do you think it's going wrong there?

Regards,
André

**Comment by Apollon77** [comment]
Controller from wherer to where?

**Comment by agross** [comment]
3.3.21 to 3.3.22

**Comment by Apollon77** [comment]
could I get the kog fully? but no nothing known like this so far. Is it reproducable? Anything in the iobroker log?

**Comment by agross** [comment]
Iobroker has exited at this point in time according to the update script, so no log there. I pasted the whole output on the command line, minus duplicated lines.

**Comment by buanet** [comment]
Any news here? Don't see this as a Docker Image issue. Can this be closed?

Regards,
André

**Comment by agross** [comment]
What news? Did change anything w.r.t. the maintenance script?

Just executed it again

```sh
$ docker exec -it iobroker_app_1 bash
root@iobroker:/opt/iobroker# iob --version
3.3.22
root@iobroker:/opt/iobroker# env
IOB_STATESDB_HOST=localhost
HOSTNAME=iobroker
IOB_STATESDB_PORT=6379
LANGUAGE=en_US:en
PACKAGES=
USBDEVICES=/dev/ttyUSB0
PWD=/opt/iobroker
SETUID=1000
TZ=Europe/Berlin
HOME=/root
LANG=en_US.UTF-8
IOB_ADMINPORT=8081
TERM=xterm
IOB_STATESDB_TYPE=redis
SHLVL=1
LC_ALL=en_US.UTF-8
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
SETGID=1000
DEBIAN_FRONTEND=teletype
_=/usr/bin/env
root@iobroker:/opt/iobroker# maintenance upgrade --yes
You are now going to upgrade your js-controller.
As this will change data in /opt/iobroker, make sure you have a backup!
During the upgrade process the container will automatically switch into maintenance mode and stop ioBroker.
Depending of the restart policy, you container will be stoped/ restarted automatically after the upgrade.
Do you want to continue [yes/no]? yes
Activating maintenance mode...
Done.
Stopping ioBroker...
Done.
Upgrading js-controller...
 Objects database error: connect ECONNREFUSED 127.0.0.1:9001
 Objects database error: connect ECONNREFUSED 127.0.0.1:9001
 Objects database error: connect ECONNREFUSED 127.0.0.1:9001
 Objects database error: connect ECONNREFUSED 127.0.0.1:9001
 Objects database error: connect ECONNREFUSED 127.0.0.1:9001
 Objects database error: connect ECONNREFUSED 127.0.0.1:9001
 Objects database error: connect ECONNREFUSED 127.0.0.1:9001
 Objects database error: connect ECONNREFUSED 127.0.0.1:9001
 Objects database error: connect ECONNREFUSED 127.0.0.1:9001
 Objects database error: connect ECONNREFUSED 127.0.0.1:9001
 Objects database error: connect ECONNREFUSED 127.0.0.1:9001
 Objects database error: connect ECONNREFUSED 127.0.0.1:9001
 Objects database error: connect ECONNREFUSED 127.0.0.1:9001
 Objects database error: connect ECONNREFUSED 127.0.0.1:9001
 Objects database error: connect ECONNREFUSED 127.0.0.1:9001
 Objects database error: connect ECONNREFUSED 127.0.0.1:9001
 Objects database error: connect ECONNREFUSED 127.0.0.1:9001
 Objects database error: connect ECONNREFUSED 127.0.0.1:9001
 Cannot find view "system" for search "host" : Connection is closed.
Error: Object "system.config" not found
```

This is the log of the container:

```
...
Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
================================== > LOG REDIRECT system.adapter.admin.0 => false [Process stopped]
================================== > LOG REDIRECT system.adapter.admin.0 => false [system.adapter.admin.0.logging]
================================== > LOG REDIRECT system.adapter.javascript.0 => false [Process stopped]
================================== > LOG REDIRECT system.adapter.javascript.0 => false [system.adapter.javascript.0.logging]
```

**Comment by agross** [comment]
The above was executed in a container that ran for 11 days.

I just restarted the ioBroker container and ran the maintenance script. Maintenance went through. This was logged

```
hash changed or no sources cached => force download of new sources
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: DB closed
    at Object.maybeCallbackWithError (/opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:2335:17)
    at StateRedisClient.setState (/opt/iobroker/node_modules/@iobroker/db-states-redis/lib/states/statesInRedisClient.js:460:26)
    at Adapter.setForeignState (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:6531:35)

Error: Connection is closed.
    at Redis.sendCommand (/opt/iobroker/node_modules/ioredis/built/redis/index.js:628:24)
    at Redis.scan (/opt/iobroker/node_modules/ioredis/built/commander.js:122:25)
    at ScanStream._read (/opt/iobroker/node_modules/ioredis/built/ScanStream.js:36:41)
    at ScanStream.Readable.read (internal/streams/readable.js:465:10)
    at resume_ (internal/streams/readable.js:963:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)

================================== > LOG REDIRECT system.adapter.admin.0 => false [Process stopped]
================================== > LOG REDIRECT system.adapter.admin.0 => false [system.adapter.admin.0.logging]
================================== > LOG REDIRECT system.adapter.javascript.0 => false [Process stopped]
================================== > LOG REDIRECT system.adapter.javascript.0 => false [system.adapter.javascript.0.logging]
Terminated

Recived termination signal (SIGTERM).
Shutting down ioBroker...
/opt/scripts/iobroker_startup.sh: line 497: kill: `': not a pid or valid job spec
```

The last line a a bit troublesome.

Also the container was not restarted as stated by maintenance, but I guess this is due to my docker `restart_policy`.

With the updated container, I restarted ioB and let it run for a minute or two to again start the maintenance script.

```sh
root@iobroker:/opt/iobroker# maintenance upgrade --yes
You are now going to upgrade your js-controller.
As this will change data in /opt/iobroker, make sure you have a backup!
During the upgrade process the container will automatically switch into maintenance mode and stop ioBroker.
Depending of the restart policy, you container will be stoped/ restarted automatically after the upgrade.
Do you want to continue [yes/no]? yes
Activating maintenance mode...
Done.
Stopping ioBroker...
Done.
Upgrading js-controller...
Used repository: beta
 Objects database error: connect ECONNREFUSED 127.0.0.1:9001
 Objects database error: connect ECONNREFUSED 127.0.0.1:9001
 Objects database error: connect ECONNREFUSED 127.0.0.1:9001
 Objects database error: connect ECONNREFUSED 127.0.0.1:9001
 Objects database error: connect ECONNREFUSED 127.0.0.1:9001
 Objects database error: connect ECONNREFUSED 127.0.0.1:9001
 Objects database error: connect ECONNREFUSED 127.0.0.1:9001
 Objects database error: connect ECONNREFUSED 127.0.0.1:9001
 Objects database error: connect ECONNREFUSED 127.0.0.1:9001
 Objects database error: connect ECONNREFUSED 127.0.0.1:9001
 Objects database error: connect ECONNREFUSED 127.0.0.1:9001
 Objects database error: connect ECONNREFUSED 127.0.0.1:9001
 Objects database error: connect ECONNREFUSED 127.0.0.1:9001
 Objects database error: connect ECONNREFUSED 127.0.0.1:9001
 Objects database error: connect ECONNREFUSED 127.0.0.1:9001
 Objects database error: connect ECONNREFUSED 127.0.0.1:9001
 Objects database error: connect ECONNREFUSED 127.0.0.1:9001
 Objects database error: connect ECONNREFUSED 127.0.0.1:9001
Error: Object "system.config" not found
hash changed or no sources cached => force download of new sources
update done
 Cannot find view "system" for search "instance" : Connection is closed.
Error: Cannot find view "system"
    at ObjectsInRedisClient._getObjectView (/opt/iobroker/node_modules/@iobroker/db-objects-redis/lib/objects/objectsInRedisClient.js:3294:64)
Adapter    "accuweather"   : 1.2.3    , installed 1.2.3
Adapter    "adb"           : 0.0.5    , installed 0.0.5
Adapter    "adguard"       : 0.0.8    , installed 0.0.8
Adapter    "admin"         : 5.2.3    , installed 5.2.3
Adapter    "backitup"      : 2.2.4    , installed 2.2.4
Adapter    "daswetter"     : 3.0.9    , installed 3.0.9
Adapter    "devices"       : 1.0.9    , installed 1.0.9
Adapter    "discovery"     : 2.7.5    , installed 2.7.5
Adapter    "dwd"           : 2.7.7    , installed 2.7.7
Adapter    "ecovacs-deebot": 1.3.3    , installed 1.3.3
Adapter    "email"         : 1.0.10   , installed 1.0.10
Adapter    "feiertage"     : 1.1.0    , installed 1.1.0
Adapter    "hm-rega"       : 3.0.35   , installed 3.0.35
Adapter    "hm-rpc"        : 1.15.2   , installed 1.15.2
Adapter    "ical"          : 1.11.6   , installed 1.11.6
Adapter    "influxdb"      : 2.4.0    , installed 2.4.0
Adapter    "info"          : 1.9.18   , installed 1.9.18
Adapter    "javascript"    : 5.2.21   , installed 5.2.21
Controller "js-controller" : 3.3.22   , installed 3.3.22
Adapter    "kodi"          : 2.0.8    , installed 2.0.8
Adapter    "zigbee"        : 1.6.14   , installed 1.6.14
Host    "iobroker"       is up to date.
Done.
Container will be stopped/ restarted in 5 seconds...
Terminated
root@iobroker:/opt/iobroker#
```

**Comment by buanet** [comment]
> Also the container was not restarted as stated by maintenance, but I guess this is due to my docker restart_policy.

Sure. Just set it to "always" and the container will do the restart.

I think it's not the maintenance script.
The script is just calling iobroker commands.
Did you try it this way?

```
maint on
iobroker update
iobroker upgrade self
[restart container]
```

Think this will give you the same output.

 But wait... Did you check? Looks like you are up to date??

```
Adapter    "accuweather"   : 1.2.3    , installed 1.2.3
Adapter    "adb"           : 0.0.5    , installed 0.0.5
Adapter    "adguard"       : 0.0.8    , installed 0.0.8
Adapter    "admin"         : 5.2.3    , installed 5.2.3
Adapter    "backitup"      : 2.2.4    , installed 2.2.4
Adapter    "daswetter"     : 3.0.9    , installed 3.0.9
Adapter    "devices"       : 1.0.9    , installed 1.0.9
Adapter    "discovery"     : 2.7.5    , installed 2.7.5
Adapter    "dwd"           : 2.7.7    , installed 2.7.7
Adapter    "ecovacs-deebot": 1.3.3    , installed 1.3.3
Adapter    "email"         : 1.0.10   , installed 1.0.10
Adapter    "feiertage"     : 1.1.0    , installed 1.1.0
Adapter    "hm-rega"       : 3.0.35   , installed 3.0.35
Adapter    "hm-rpc"        : 1.15.2   , installed 1.15.2
Adapter    "ical"          : 1.11.6   , installed 1.11.6
Adapter    "influxdb"      : 2.4.0    , installed 2.4.0
Adapter    "info"          : 1.9.18   , installed 1.9.18
Adapter    "javascript"    : 5.2.21   , installed 5.2.21
Controller "js-controller" : 3.3.22   , installed 3.3.22
Adapter    "kodi"          : 2.0.8    , installed 2.0.8
Adapter    "zigbee"        : 1.6.14   , installed 1.6.14
Host    "iobroker"       is up to date.
Done.
```

Regards,
André

**Comment by buanet** [comment]
@agross Ich habe gerade mal auf meinem Testsystem die verschiedenen Möglichkeiten vom Upgrade ausprobiert und siehe da, ich konnte den Fehler (zumindest zwei Mal) reproduzieren... aber nur wenn ich 'maint upgrade -y' nutze. 
Kannst du das bestätigen?

Wenn ich 'maint on' und dann 'maint upgrade' nutze passiert das nicht. 

Meine Theorie ist nun dass das Script in diesem Scenario in irgendeiner Form zu schnell ist (???) :)
Baue ich im Script zwei sleep ein, bekomme ich den Fehler nicht mehr reproduziert. 

Traust du dir zu das maintenance Script im Container unter  '/opt/scripts/maintenance.sh' einmal manuell anzupassen (ziemlich weit unten) und zweimal 'sleep 1' einzufügen?

https://github.com/buanet/ioBroker.docker/blob/15e87e08a0d7c4f6719631144903121a20828a20/debian/scripts/maintenance.sh#L160

```
  echo 'Upgrading js-controller...'
  sleep 1
  iobroker update
  sleep 1
  iobroker upgrade self
  sleep 1
  echo 'Done.'
```

Wie verhält es sich dann bei dir?

MfG,
André

**Comment by agross** [comment]
Ich weiß nicht, ob `--yes` was damit zu tun hat. Wie oben angezeigt musste ich das in meinem Container immer manuell bestätigen (Was ja eigentlich am Ziel von `--yes` vorbei geht. Aber ich glaube dazu hatten wir schon mal ein Issue.)

Ich hab dein Image heute aktualisiert und werde es gleich nochmal mit und ohne `sleep` im Script ausprobieren.

**Comment by buanet** [comment]
> Ich weiß nicht, ob --yes was damit zu tun hat. Wie oben angezeigt musste ich das in meinem Container immer manuell bestätigen (Was ja eigentlich am Ziel von --yes vorbei geht. Aber ich glaube dazu hatten wir schon mal ein Issue.)

Nutzt du das Beta Image? Da sollte es schon drin sein.

https://github.com/buanet/ioBroker.docker/releases/tag/v6.1.0-beta.1

**Comment by agross** [comment]
> Wie verhält es sich dann bei dir?

Das zusätzliche `sleep 1` zwischen `iobroker update` und `iobroker upgrade self` hat leider nichts gebracht. Ob das sleep nach `pkill` was bringt wage ich zu bezweifeln.

Die ganze Fehler von wegen connection refused kommen übrigens alle während `iobroker update` läuft (und praktisch hängt), also noch vor `upgrade self`. Von der PID 1 (iobroker) ist zu diesem Zeitpunkt schon nichts mehr zu sehen, wurde also gekillt.

**Comment by buanet** [comment]
Die "manuelle Optimierung" oben ist obsolete.

Wenn ich das richtig gesehen habe, dann kommt der Fehler wenn ich zu schnell hinter `pkill -u iobroker` den `iobroker update` ausführe. [Daher habe ich da jetzt eine Zwangspause von 5 Sekunden drin.](https://github.com/buanet/ioBroker.docker/blob/57c3fe23717d902a250dd3debb540bee42b513bb/debian/scripts/maintenance.sh#L157) Das würde auch erklären warum der Fehler nicht passiert wenn man vorher ein `m on` macht. Dann ist der iobroker beim `m upgrade` nämlich schon gestoppt. Mit dem sleep habe ich den Fehler nicht mehr reproduzieren können...

> Das zusätzliche sleep 1 zwischen iobroker update und iobroker upgrade self hat leider nichts gebracht. Ob das sleep nach pkill was bringt wage ich zu bezweifeln.

Brauchst du nicht bezweifeln. Das hat in diesem Fall keinen Einfluss.

**Comment by agross** [comment]
OK, dann lassen wir es auf einen Versuch ankommen. Hoffentlich wird bald ein neue js-controller-Version released, dann patche ich `maintenance.sh` in meinem Container und versuche es mit dem Upgrade.

**Comment by agross** [comment]
Ja, ich denke 5 Sekunden sind ein Wert der in vielleicht 90% der Fälle passt. Vielleicht aber auch nicht für Instanzen mit vielen Plugins. Besser wäre tatsächlich zu warten bis alles beendet ist. Ich bastel gerade ein Sample.

**Comment by agross** [comment]
Klar, das betrifft auch docker. Aber da kann man ja das stop-timeout definieren falls es für dich diese eigenen Instanz nicht ausreicht.

**Comment by Apollon77** [comment]
Naja das ist am Ende "ok". Ein SIGKILL ruft den gleichen internen shutdown Prozess auf mit "force" flag welches nochmal ausgibt welche adapter ggf noch laufen das aber ignoriert und sich dann direkt beendet.

**Comment by Apollon77** [comment]
PS: Wie auch gesagt reichen die 10s denke ich für 9x% aller Fälle aus ...

**Comment by buanet** [comment]
Docker Image [v7.0.0](https://github.com/buanet/ioBroker.docker/releases/tag/v7.0.0) is now latest. So I think this is done. :) 
Thank you!

Regards,
André

**Comment by agross** [comment]
Thank you, too! 👍🏻
