### ISSUE TITLE
updated iobroker from 5.x to latest 7.x after update admin iobroker is not reachable anymore 

### ISSUE THREAD

**Issue by haarchri** [buanet/ioBroker.docker#278]
updated iobroker from 5.x to latest 7.x after update admin iobroker is not reachable anymore - only output in logs:

```
Starting ioBroker...


 


host.store check instance "system.adapter.admin.0" for host "store"


host.store check instance "system.adapter.history.0" for host "store"


host.store check instance "system.adapter.hm-rpc.0" for host "store"


host.store check instance "system.adapter.hm-rpc.1" for host "store"


host.store check instance "system.adapter.hm-rega.0" for host "store"


host.store check instance "system.adapter.hm-rpc.2" for host "store"


host.store check instance "system.adapter.mihome-vacuum.0" for host "store"


host.store check instance "system.adapter.discovery.0" for host "store"


host.store check instance "system.adapter.scenes.0" for host "store"


host.store check instance "system.adapter.tradfri.0" for host "store"


host.store check instance "system.adapter.iot.0" for host "store"


host.store check instance "system.adapter.javascript.0" for host "store"


host.store check instance "system.adapter.info.0" for host "store"


host.store check instance "system.adapter.influxdb.0" for host "store"


host.store check instance "system.adapter.discovergy.0" for host "store"


host.store check instance "system.adapter.km200.0" for host "store"


host.store check instance "system.adapter.klf200.0" for host "store"


host.store check instance "system.adapter.shelly.0" for host "store"


This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:




TypeError: Cannot read property '0' of undefined


    at ObjectsInRedisClient._applyViewFunc (/opt/iobroker/node_modules/@iobroker/db-objects-redis/lib/objects/objectsInRedisClient.js:3655:39)


    at processTicksAndRejections (internal/process/task_queues.js:95:5)




This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:




TypeError: Cannot read property '0' of undefined


    at ObjectsInRedisClient._applyViewFunc (/opt/iobroker/node_modules/@iobroker/db-objects-redis/lib/objects/objectsInRedisClient.js:3655:39)


    at processTicksAndRejections (internal/process/task_queues.js:95:5)




/bin/sh: 1: iw: not found




/bin/sh: 1: iw: not found




/bin/sh: 1: hcitool: not found




This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:




TypeError: Cannot read property '0' of undefined


    at ObjectsInRedisClient._applyViewFunc (/opt/iobroker/node_modules/@iobroker/db-objects-redis/lib/objects/objectsInRedisClient.js:3655:39)


    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by haarchri** [comment]
fixed it by:

```
cd /opt/iobroker
--
  | iobroker stop admin.0
  | npm install iobroker.admin
  | iobroker upload admin
  | iobroker start admin.0
```
