### ISSUE TITLE
vis kann aus Backup nicht wieder hergestellt werden

### ISSUE THREAD

**Issue by RK62** [buanet/ioBroker.docker#290]
Ich weiß nicht ob es hier hin gehört, sonst gerne einen Tip wo ich das adressieren muss.

Ich versuche vom iobroker/iobroker:v6.1.0 auf die 7.0.1 zu kommen. Ich nutze REDIS für die States. Habe aber auch schon auf die JSONL-Datenbank gewechselt, erzeugt den gleichen Fehler. Bei der V7.1.0 ist es auch das gleiche Problem.
- Backup 6.1.0 erstellt und gesichert
- neuen Ordner angelegt und Container mit der V7.0.1 erstellt und Backup 6.1.0 dort abgelegt
- Container läuft an, Restore erfolgreich und Adapter werden installiert
- Dann kommt das Problem: VIS kann mit der folgenden Fehlermeldung nicht installiert werden:

```
2022-10-30 16:36:33.690  - [33mwarn[39m: host.iobroker startInstance cannot find adapter "vis@1.4.15". Try to install it... 1 attempt
2022-10-30 16:36:33.690  - [32minfo[39m: host.iobroker iobroker install vis@1.4.15 using installedFrom
2022-10-30 16:36:34.972  - [32minfo[39m: host.iobroker iobroker npm-install: NPM version: 6.14.17
2022-10-30 16:36:34.974  - [32minfo[39m: host.iobroker iobroker npm-install: Installing iobroker.vis@1.4.15... (System call)
2022-10-30 16:36:44.808  - [32minfo[39m: host.iobroker iobroker npm-install: > iobroker.vis@1.4.15 install /opt/iobroker/node_modules/iobroker.vis
2022-10-30 16:36:44.809  - [32minfo[39m: host.iobroker iobroker npm-install: > node main.js --install
2022-10-30 16:36:45.478  - [32minfo[39m: vis.0 (2920) starting. Version 1.4.15 in /opt/iobroker/node_modules/iobroker.vis, node: v14.20.1, js-controller: 4.0.23
2022-10-30 16:36:45.638  - [32minfo[39m: vis.0 (2920) vis license is OK.
2022-10-30 16:36:45.726  - [31merror[39m: vis.0 (2920) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-10-30 16:36:45.727  - [31merror[39m: vis.0 (2920) unhandled promise rejection: Not exists
2022-10-30 16:36:45.728  - [31merror[39m: vis.0 (2920) Error: Not exists
    at Object.maybeCallbackWithError (/opt/iobroker/node_modules/@iobroker/js-controller-common/lib/common/tools.js:2973:17)
    at ObjectsInRedisClient._readFile (/opt/iobroker/node_modules/@iobroker/db-objects-redis/lib/objects/objectsInRedisClient.js:1043:26)
    at Immediate.<anonymous> (/opt/iobroker/node_modules/@iobroker/db-objects-redis/lib/objects/objectsInRedisClient.js:1092:29)
    at processImmediate (internal/timers.js:466:21)
2022-10-30 16:36:45.729  - [31merror[39m: vis.0 (2920) Not exists
2022-10-30 16:36:46.232  - [32minfo[39m: vis.0 (2920) terminating
2022-10-30 16:36:46.233  - [33mwarn[39m: vis.0 (2920) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-10-30 16:36:47.668  - [31merror[39m: host.iobroker iobroker npm-install: host.iobroker Cannot install iobroker.vis@1.4.15: 6
2022-10-30 16:36:48.685  - [32minfo[39m: host.iobroker iobroker npm-install: exit 25
```
- Zusätzliche Instanz kann auch nicht installiert werden
- Ich muss die Instanz vis.0 löschen (vorher aber alle Zusatzmodule hq-widdgets, etc) dann kann ich erfolgreich eine neue vis.0 anlegen
- In der Anlage noch das npm Protokoll
[2022-11-01T07_37_32_979Z-debug-0.log](https://github.com/buanet/ioBroker.docker/files/9907856/2022-11-01T07_37_32_979Z-debug-0.log)

**Comment by Apollon77** [comment]
An issue in is already exists. including a workaround ...  ( I think install older version 1.4.5 or such and then upgrade again)

**Comment by buanet** [comment]
Sieht wie das hier aus: https://github.com/ioBroker/ioBroker.vis/issues/459
Ist jedenfalls nicht Docker Image related, daher schließe ich es hier. 

MfG,
André
