### ISSUE TITLE
[Problem]: Error when updating adatper via GitHub

### ISSUE THREAD

**Issue by phifogg** [buanet/ioBroker.docker#341]
### Description

I tried to update one of my adapters via GitGub URL. The adapter is owned by myself and I wanted to test the next to-be released version.

The debug-log of this update has some errors in it:
```
39 verbose stack Error: An unknown git error occurred
39 verbose stack     at makeError (/usr/lib/node_modules/npm/node_modules/@npmcli/git/lib/make-error.js:28:13)
39 verbose stack     at /usr/lib/node_modules/npm/node_modules/@npmcli/git/lib/spawn.js:37:26
39 verbose stack     at processTicksAndRejections (node:internal/process/task_queues:96:5)
40 verbose cwd /opt/iobroker
41 verbose Linux 5.10.0-21-amd64
42 verbose node v16.19.0
43 verbose npm  v8.19.3
44 error code 128
45 error An unknown git error occurred
46 error command git --no-replace-objects ls-remote ssh://git@github.com/phifogg/ioBroker.sainlogic.git
47 error ssh -oStrictHostKeyChecking=accept-new: 1: ssh: not found
47 error fatal: Could not read from remote repository.
47 error
47 error Please make sure you have the correct access rights
47 error and the repository exists.
48 verbose exit 128

```

### Image version

buanet/iobroker:latest

### Docker logs

```shell
not sure this helps, is this an problem with the image or with iobroker itself?
```

**Comment by ThomasK1966** [comment]
Hi @phifogg, are you sure that you use the latest image?
I use the latest image and I have this versions:

Node.js: v18.16.0
NPM: 9.5.1

**Comment by phifogg** [comment]
Thanks... correct. It was latest when I created it 3 months ago.
Updated my image and it works now.
